import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfólio Ruan L Andrade</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="text-red-500">Lets build an AWESOME portfolio</h1>
    </div>
  )
}
